# Generated by Django 5.2.9 on 2026-01-04 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Document Asset',
                'verbose_name_plural': 'Document Assets',
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('asn', models.CharField(blank=True, max_length=64)),
                ('isp', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('is_proxy', models.BooleanField(default=False)),
                ('is_tor', models.BooleanField(default=False)),
                ('user_agent', models.TextField(blank=True)),
                ('accept_headers', models.TextField(blank=True)),
                ('accept_language', models.CharField(blank=True, max_length=128)),
                ('tls_fingerprint', models.CharField(blank=True, max_length=128)),
                ('os_name', models.CharField(blank=True, max_length=64)),
                ('os_version', models.CharField(blank=True, max_length=64)),
                ('browser_name', models.CharField(blank=True, max_length=64)),
                ('browser_version', models.CharField(blank=True, max_length=64)),
                ('client_app', models.CharField(blank=True, max_length=128)),
                ('client_build', models.CharField(blank=True, max_length=64)),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('request_body', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('clock_skew', models.IntegerField(blank=True, null=True)),
                ('is_first_access', models.BooleanField(default=False)),
                ('session_id', models.CharField(blank=True, max_length=64)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='tracker.document')),
            ],
            options={
                'verbose_name': 'Document Render Event',
                'verbose_name_plural': 'Document Render Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['cid', 'timestamp'], name='tracker_acc_cid_62ca48_idx'), models.Index(fields=['ip_address', 'timestamp'], name='tracker_acc_ip_addr_d9075d_idx')],
            },
        ),
    ]
