# Generated by Django 6.0.4 on 2026-04-17 17:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_document_file_path_alter_accesslog_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(blank=True, db_index=True, max_length=64)),
                ('bot_type', models.CharField(blank=True, max_length=128)),
                ('attack_vector', models.CharField(blank=True, max_length=128)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('target_endpoint', models.CharField(blank=True, max_length=255)),
                ('success', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user_agent', models.TextField(blank=True)),
                ('behavior_indicators', models.JSONField(blank=True, default=list)),
                ('request_headers', models.JSONField(blank=True, default=dict)),
                ('custom_metadata', models.JSONField(blank=True, default=dict)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_signals', to='tracker.document')),
            ],
            options={
                'verbose_name': 'Bot Signal',
                'verbose_name_plural': 'Bot Signals',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['cid', 'timestamp'], name='tracker_bot_cid_e355ca_idx'), models.Index(fields=['source_ip', 'timestamp'], name='tracker_bot_source__802275_idx'), models.Index(fields=['bot_type'], name='tracker_bot_bot_typ_db9baa_idx')],
            },
        ),
    ]
